language: php
php:
  - 5.3
  - 5.4
env:
  - MAGENTO_VERSION="1.8.0.0"
  - MAGENTO_VERSION="1.8.1.0"
  - MAGENTO_VERSION="1.9.0.0"
  - MAGENTO_VERSION="1.9.0.1"
before_install:
  - mkdir magento/
  - cp -f .travis/composer.json composer.json
  - composer install --dev
before_script:
  - CURR_DIR=$(pwd)
  - bin/mage-ci install magento $MAGENTO_VERSION magento_test -c -t -r http://mage-ci.ecomdev.org
  - bin/mage-ci install-module magento $CURR_DIR
  - git clone git://github.com/IvanChepurnyi/EcomDev_PHPUnit.git -b dev ./phpunit/
  - bin/mage-ci install-module $CURR_DIR/magento $CURR_DIR/phpunit/
script:
  - bin/mage-ci phpunit magento